StartSexSpells = {
    {
        AnimName = "StartMasturbation",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Solo",
        TopAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002",
        BottomAnimationID = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b"
    },
    {
        AnimName = "AskForSex",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = false,
        SoundTop = {"Instrument_Bard_Silence","Instrument_Bard_Silence"},
        SoundBottom = {"Instrument_Bard_Silence","Instrument_Bard_Silence"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "49d78660-5175-4ed2-9853-840bb58cf34a",
        BottomAnimationID = "10fee5b7-d674-436c-994c-616e01efcb90"
    },
}

SexAnimations = {
    {
        AnimName = "Grinding",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Solo",
        TopAnimationID = "0114c60d-0f82-4827-ae11-9e3c46f7d7b5",
        BottomAnimationID = "8b9b1bb2-842b-422c-90ff-efbbe84835aa"
    },
    {
        AnimName = "EatPussy",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "5fa5cbe4-1baf-4529-b448-2c53e163626c",
        BottomAnimationID = "f801ec0d-9fee-4584-bae3-96d7c3e285ff"
    },
    {
        AnimName = "FingerFuck",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "adf1b790-da1d-4aaf-9ac4-83157c52d5c2",
        BottomAnimationID = "a79232a2-a498-4689-a5bd-8923e80284d2"
    },
    {
        AnimName = "Blowjob",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "536f0403-c401-4223-bbca-6b807494a527",
        BottomAnimationID = "b3984708-7664-49ae-b96d-0512497ea036"
    },
    {
        AnimName = "Missionary",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "905be226-3edc-4783-9d4e-45d2b57a3d0a",
        BottomAnimationID = "48a255e9-02ec-4541-b1b7-32275da29206"
    },
    {
        AnimName = "Doggy",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "b8f04918-c5b6-4c4a-aee5-390bfaff33bc",
        BottomAnimationID = "ffdd67e7-7363-46a4-92e2-38260ef0a2e0"
    },
    {
        AnimName = "Cowgirl",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "ff7a5a30-b661-4192-bd8f-118373e3f4b8",
        BottomAnimationID = "1b220386-55fa-4d2b-8da4-0e7bf453d928"
    },
    {
        AnimName = "StopMasturbating",
    },
    {
        AnimName = "MasturbateOnBack",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Solo",
        TopAnimationID = "",
    },
    {
        AnimName = "MasturbateStanding",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Solo",
        TopAnimationID = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b",
        BottomAnimationID = "dab6d199-fb66-4181-b4e1-fc3c3a831cbd",
    },
    {
        AnimName = "Milking",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Paired",
        TopAnimationID = "a71ace41-41ce-4876-8f14-4f419b677533",
        BottomAnimationID = "d2a17851-b51b-4e4f-be1d-30dc86b6466a"
    },
    {
        AnimName = "Wanking",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Solo",
        TopAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002",
        BottomAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002"
    },
	

}