StartSexSpells = {
    {
        AnimName = "StartMasturbation",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Solo",
        FallbackTopAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002",
        FallbackBottomAnimationID = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b",
        Med_Female = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b",
        Med_Male = "49497bdc-d901-4f60-9e4e-3d31a06f9002",
    },
    {
        AnimName = "AskForSex",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = false,
        SoundTop = {"Instrument_Bard_Silence","Instrument_Bard_Silence"},
        SoundBottom = {"Instrument_Bard_Silence","Instrument_Bard_Silence"},
        Strip = true,
        Type = "Paired",
        FallbackTopAnimationID = "49d78660-5175-4ed2-9853-840bb58cf34a",
        FallbackBottomAnimationID = "10fee5b7-d674-436c-994c-616e01efcb90",
        MedTop_MedBtm = {
            Btm = "10fee5b7-d674-436c-994c-616e01efcb90",
            Top = "49d78660-5175-4ed2-9853-840bb58cf34a",
        },
        TallTop_MedBtm = {
            Btm = "392073ca-c6e0-4f7d-848b-ffb0b510500b",
            Top = "04922882-0a2d-4945-8790-cef50276373d",
        },
    },
}

SexAnimations = {
    {
        AnimName = "FingerFuck",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundBottom = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        FallbackTopAnimationID = "adf1b790-da1d-4aaf-9ac4-83157c52d5c2",
        FallbackBottomAnimationID = "a79232a2-a498-4689-a5bd-8923e80284d2"
    },
    {
        AnimName = "Blowjob",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        Strip = true,
        Type = "Paired",
        FallbackTopAnimationID = "536f0403-c401-4223-bbca-6b807494a527",
        FallbackBottomAnimationID = "b3984708-7664-49ae-b96d-0512497ea036"
    },
    {
        AnimName = "MasturbateStanding",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"BreathLongExhaleOpen_PlayerCharacter_Cine","BreathLongInhaleOpen_PlayerCharacter_Cine","LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanClosed_PlayerCharacter_Cine", "LoveMoanOpen_PlayerCharacter_Cine"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Solo",
        FallbackTopAnimationID = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b",
        FallbackBottomAnimationID = "9d8c5992-55ab-4c2f-8d97-28b68eb50a8b",
    },
    {
        AnimName = "Wanking",
        AnimLength = 3600,
        Loop = true,
        Fade = true,
        Sound = true,
        SoundTop = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        SoundBottom = {"CAMP_Karlach_CRD_ROM_Date_SexKiss2", "CAMP_Karlach_CRD_ROM_Date_SexKiss3", "CAMP_Karlach_CRD_ROM_Date_SexKiss6", "CAMP_Karlach_CRD_ROM_Date_SexKiss7", "CAMP_Karlach_CRD_ROM_Date_SexKiss9"},
        Strip = true,
        Type = "Solo",
        FallbackTopAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002",
        FallbackBottomAnimationID = "49497bdc-d901-4f60-9e4e-3d31a06f9002"
    },
}